import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'
import SignForm from '../components/SignForm/SignForm'

export default function Home() {
  return (
    <>
    <Navbar />
    <div className={styles.container}>
      <Head>
        <title>IT Tickets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.backgroundImg}>
      <div className={styles.overlay}>
      <main className={styles.main}>
        <div className={styles.welcome}>
        <div className={styles.signUp}>
          <div> <h1 className={styles.title}>
        The #1 <a href="https://nextjs.org">Portal</a> used by IT teams
        </h1>
        <p className={styles.description}>
          Bring perfection to your webapp
        </p></div>
        <SignForm />
        </div>
        </div>
        </main>
        </div>
        </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </>
    
  )
}
